from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

from tools.check_generated_artifacts import validate_generated_artifacts
from tools.desys_indexer.config import SUPPORTED_ARTIFACTS, load_config
from tools.desys_indexer.parser import parse_documents
from tools.desys_indexer.scanner import scan_markdown_documents
from tools.desys_indexer.writer import render_indexes, write_indexes
from tools.init_project import ProjectInitializationError, initialize_project

TEST_VERSION = "0.1.0a1"


def make_repository(directory: Path) -> Path:
    directory.mkdir()
    subprocess.run(
        ["git", "init", "--quiet", str(directory)],
        check=True,
        capture_output=True,
        text=True,
    )
    return directory


def test_dry_run_reports_plan_without_writing(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")

    plan = initialize_project(root, dry_run=True, version=TEST_VERSION)

    assert not plan.has_conflicts
    assert all(operation.action == "CREATE" for operation in plan.operations)
    assert [path.name for path in root.iterdir()] == [".git"]


def test_initializes_a_loadable_consumer_configuration(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")

    first = initialize_project(root, version=TEST_VERSION)
    config = load_config(root / "tools/desys_indexer.yaml")

    assert not first.has_conflicts
    assert config.repository_root == root.resolve()
    assert config.artifacts == SUPPORTED_ARTIFACTS
    assert {path.relative_to(root.resolve()).as_posix() for path in config.sources} == {
        "docs/adr",
        "docs/prd",
        "docs/rfc",
    }
    gitignore = (root / ".gitignore").read_text(encoding="utf-8")
    assert "/docs/generated/" in gitignore
    assert "Regenerated by scripts/desys-docs-quality.sh" in gitignore
    assert (root / "tools/desys-source.txt").read_text(encoding="utf-8") == (
        "dundercode-engineering-system==0.1.0a1\n"
    )

    documents = parse_documents(
        scan_markdown_documents(config), repository_root=config.repository_root
    )
    rendered = render_indexes(documents, config.artifacts)
    write_indexes(rendered=rendered, output_dir=config.output_directory)
    summary = validate_generated_artifacts(config.output_directory)

    assert summary["document_count"] == 0
    assert summary["artifact_count"] == 5
    quality_script = (root / "scripts/desys-docs-quality.sh").read_text(encoding="utf-8")
    assert '${BASH_SOURCE[0]}' in quality_script
    assert "uvx --isolated --no-config --python 3.12" in quality_script
    assert "uv sync" not in quality_script
    workflow = (root / ".github/workflows/desys-docs-quality.yml").read_text(encoding="utf-8")
    assert "actions/setup-python" not in workflow
    assert "cache-dependency-glob: tools/desys-source.txt" in workflow
    assert "  push:\n" in workflow
    assert "    branches:\n" not in workflow
    agents = (root / "AGENTS.md").read_text(encoding="utf-8")
    assert "docs/generated/search-index.json" in agents
    assert "source Markdown is authoritative" in agents
    assert "Cite repository-relative paths" in agents
    assert "source --relationship--> target" in agents
    assert "`draft`, `review`, `approved`, `published`,\nand `deprecated`" in agents
    assert "`legacy_status: true`" in agents
    assert "Neither field alone establishes whether a document is binding" in agents
    assert "Determine authority from explicit project\ngovernance evidence" in agents
    assert "does not imply unilateral approval\npower" in agents
    assert "do not define a required transition sequence" in agents
    assert "approval process, or mandatory artifact type" in agents
    assert "optional proposals that\nrequire confirmation" in agents
    assert "only when the documented project process or requested task requires" in agents
    assert "require explicit confirmation" in agents
    assert "cannot make them authoritative" in agents
    assert "Metadata schema v1 requires `language: en`" in agents
    assert "write source document prose in\n   English" in agents
    assert "Do not label non-English content as `en`" in agents
    assert "`approved` and `published` documents govern" not in agents


def test_second_run_is_idempotent(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    initialize_project(root, version=TEST_VERSION)
    files = tuple(
        path for path in root.rglob("*") if path.is_file() and ".git" not in path.parts
    )
    before = {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in files}

    plan = initialize_project(root, version=TEST_VERSION)

    assert not plan.has_conflicts
    assert all(operation.action == "UNCHANGED" for operation in plan.operations)
    assert {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in files} == before


def test_conflict_prevents_all_writes(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    tools = root / "tools"
    tools.mkdir()
    config = tools / "desys_indexer.yaml"
    config.write_text("consumer-owned: true\n", encoding="utf-8")

    plan = initialize_project(root, version=TEST_VERSION)

    assert plan.has_conflicts
    assert config.read_text(encoding="utf-8") == "consumer-owned: true\n"
    assert not (root / "docs").exists()
    assert not (root / ".gitignore").exists()


def test_extends_existing_gitignore_once(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    gitignore = root / ".gitignore"
    gitignore.write_text(".venv/\n", encoding="utf-8")

    first = initialize_project(root, version=TEST_VERSION)
    second = initialize_project(root, version=TEST_VERSION)
    content = gitignore.read_text(encoding="utf-8")

    assert "UPDATE" in {operation.action for operation in first.operations}
    assert not second.has_conflicts
    assert content.count("/docs/generated/") == 1
    assert content.count("Regenerated by scripts/desys-docs-quality.sh") == 1
    assert content.startswith(".venv/\n\n")


def test_extends_existing_agents_file_once(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    agents = root / "AGENTS.md"
    agents.write_text("# Existing Agent Instructions\n", encoding="utf-8")

    first = initialize_project(root, version=TEST_VERSION)
    second = initialize_project(root, version=TEST_VERSION)
    content = agents.read_text(encoding="utf-8")

    agents_operation = next(operation for operation in first.operations if operation.path.as_posix() == "AGENTS.md")
    assert agents_operation.action == "UPDATE"
    assert not second.has_conflicts
    assert content.startswith("# Existing Agent Instructions\n\n")
    assert content.count("<!-- BEGIN DESys documentation instructions -->") == 1
    assert content.count("<!-- END DESys documentation instructions -->") == 1


def test_rejects_malformed_agents_markers_without_writing(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    agents = root / "AGENTS.md"
    original = "<!-- BEGIN DESys documentation instructions -->\nIncomplete\n"
    agents.write_text(original, encoding="utf-8")

    plan = initialize_project(root, version=TEST_VERSION)

    assert plan.has_conflicts
    assert agents.read_text(encoding="utf-8") == original
    assert not (root / "docs").exists()


def test_preserves_full_sha_git_source(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    source = (
        "dundercode-engineering-system @ "
        f"git+https://github.com/DunderCode-Solutions/dundercode-engineering-system.git@{'a' * 40}"
    )

    initialize_project(root, version=TEST_VERSION, desys_source=source)

    assert (root / "tools/desys-source.txt").read_text(encoding="utf-8") == f"{source}\n"


def test_accepts_repository_relative_wheel_source(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    vendor = root / "tools/vendor"
    vendor.mkdir(parents=True)
    wheel = vendor / "dundercode_engineering_system-0.1.0a1-py3-none-any.whl"
    wheel.write_bytes(b"pilot wheel")
    source = wheel.relative_to(root).as_posix()

    initialize_project(root, version=TEST_VERSION, desys_source=source)

    assert (root / "tools/desys-source.txt").read_text(encoding="utf-8") == f"{source}\n"


def test_rejects_mutable_or_unsafe_sources_before_writing(tmp_path: Path) -> None:
    invalid_sources = (
        "",
        " dundercode-engineering-system==0.1.0a1",
        "dundercode-engineering-system>=0.1.0a1",
        "dundercode-engineering-system==1..0",
        "dundercode-engineering-system==01.2.3",
        "dundercode-engineering-system==0.2.0",
        "dundercode-engineering-system @ git+https://example.com/desys.git@main",
        "dundercode-engineering-system @ git+http://example.com/desys.git@" + "a" * 40,
        "dundercode-engineering-system @ git+https://example.com/desys.git?token=secret@" + "a" * 40,
        "/tmp/desys.whl",
        "../desys.whl",
        "tools/desys release.whl",
        "desys\nsecond-line",
    )

    for index, source in enumerate(invalid_sources):
        root = make_repository(tmp_path / f"repository-{index}")
        with pytest.raises(ProjectInitializationError):
            initialize_project(root, version=TEST_VERSION, desys_source=source)
        assert [path.name for path in root.iterdir()] == [".git"]


def test_source_change_is_a_non_destructive_conflict(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    initialize_project(root, version=TEST_VERSION)
    source_file = root / "tools/desys-source.txt"
    original = source_file.read_bytes()
    git_source = (
        "dundercode-engineering-system @ "
        f"git+https://example.com/desys.git@{'b' * 40}"
    )

    plan = initialize_project(root, version=TEST_VERSION, desys_source=git_source)

    source_operation = next(
        operation for operation in plan.operations if operation.path.as_posix() == "tools/desys-source.txt"
    )
    assert plan.has_conflicts
    assert source_operation.action == "CONFLICT"
    assert source_file.read_bytes() == original


def fake_uvx_environment(tmp_path: Path) -> tuple[dict[str, str], Path]:
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    marker = tmp_path / "uvx-called"
    fake_uvx = fake_bin / "uvx"
    fake_uvx.write_text('#!/usr/bin/env bash\nprintf "%s\\n" "$*" >> "$UVX_MARKER"\n', encoding="utf-8")
    fake_uvx.chmod(0o755)
    return (
        {
            **os.environ,
            "PATH": f"{fake_bin}:{os.environ['PATH']}",
            "UVX_MARKER": str(marker),
        },
        marker,
    )


def test_quality_script_accepts_source_without_terminal_newline(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    initialize_project(root, version=TEST_VERSION)
    source_file = root / "tools/desys-source.txt"
    source_file.write_text("dundercode-engineering-system==0.1.0a1", encoding="utf-8")
    environment, marker = fake_uvx_environment(tmp_path)

    result = subprocess.run(
        ["bash", str(root / "scripts/desys-docs-quality.sh")],
        cwd=tmp_path,
        check=False,
        capture_output=True,
        text=True,
        env=environment,
    )

    assert result.returncode == 0, result.stderr
    assert marker.read_text(encoding="utf-8").count("dundercode-engineering-system==0.1.0a1") == 3


def test_quality_script_rejects_tampered_source_before_uvx(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    initialize_project(root, version=TEST_VERSION)
    (root / "tools/desys-source.txt").write_text(
        "dundercode-engineering-system>=0.1.0a1\n",
        encoding="utf-8",
    )
    environment, marker = fake_uvx_environment(tmp_path)

    result = subprocess.run(
        ["bash", str(root / "scripts/desys-docs-quality.sh")],
        cwd=tmp_path,
        check=False,
        capture_output=True,
        text=True,
        env=environment,
    )

    assert result.returncode == 1
    assert "Unsupported or mutable DESys source" in result.stderr
    assert not marker.exists()


def test_quality_script_rejects_multiple_source_lines_before_uvx(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    initialize_project(root, version=TEST_VERSION)
    (root / "tools/desys-source.txt").write_text(
        "dundercode-engineering-system==0.1.0a1\nsecond-source\n",
        encoding="utf-8",
    )
    environment, marker = fake_uvx_environment(tmp_path)

    result = subprocess.run(
        ["bash", str(root / "scripts/desys-docs-quality.sh")],
        cwd=tmp_path,
        check=False,
        capture_output=True,
        text=True,
        env=environment,
    )

    assert result.returncode == 1
    assert "must contain exactly one non-empty line" in result.stderr
    assert not marker.exists()


def test_rejects_non_git_root(tmp_path: Path) -> None:
    with pytest.raises(ProjectInitializationError):
        initialize_project(tmp_path, dry_run=True, version=TEST_VERSION)


def test_cli_returns_failure_for_non_git_root(tmp_path: Path) -> None:
    result = subprocess.run(
        [sys.executable, "-m", "tools.init_project", "--root", str(tmp_path), "--dry-run"],
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 1
    assert "must contain a non-symlinked .git entry" in result.stderr


def test_rejects_symlinked_managed_path(tmp_path: Path) -> None:
    root = make_repository(tmp_path / "repository")
    external = tmp_path / "external"
    external.mkdir()
    (root / "docs").symlink_to(external, target_is_directory=True)

    plan = initialize_project(root, version=TEST_VERSION)

    assert plan.has_conflicts
    assert not (root / "tools").exists()
